=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::AccountRechargeApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::SwaggerClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::SwaggerClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# recharge_credit_card_get
#
# Get Credit Card info
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'recharge_credit_card_get' } = { 
    	summary => 'Get Credit Card info',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_credit_card_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/recharge/credit-card';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# recharge_credit_card_put
#
# Update credit card info
# 
# @param CreditCard $credit_card CreditCard model (required)
{
    my $params = {
    'credit_card' => {
        data_type => 'CreditCard',
        description => 'CreditCard model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'recharge_credit_card_put' } = { 
    	summary => 'Update credit card info',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_credit_card_put {
    my ($self, %args) = @_;

    # verify the required parameter 'credit_card' is set
    unless (exists $args{'credit_card'}) {
      croak("Missing the required parameter 'credit_card' when calling recharge_credit_card_put");
    }

    # parse inputs
    my $_resource_path = '/recharge/credit-card';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'credit_card'}) {
        $_body_data = $args{'credit_card'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# recharge_packages_get
#
# Get list of all packages
# 
# @param string $country Country code (optional)
{
    my $params = {
    'country' => {
        data_type => 'string',
        description => 'Country code',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'recharge_packages_get' } = { 
    	summary => 'Get list of all packages',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_packages_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/recharge/packages';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'country'}) {
        $query_params->{'country'} = $self->{api_client}->to_query_value($args{'country'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# recharge_purchase_by_package_id_put
#
# Purchase a package
# 
# @param int $package_id ID of package to purchase (required)
{
    my $params = {
    'package_id' => {
        data_type => 'int',
        description => 'ID of package to purchase',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'recharge_purchase_by_package_id_put' } = { 
    	summary => 'Purchase a package',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_purchase_by_package_id_put {
    my ($self, %args) = @_;

    # verify the required parameter 'package_id' is set
    unless (exists $args{'package_id'}) {
      croak("Missing the required parameter 'package_id' when calling recharge_purchase_by_package_id_put");
    }

    # parse inputs
    my $_resource_path = '/recharge/purchase/{package_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'package_id'}) {
        my $_base_variable = "{" . "package_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'package_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# recharge_transactions_by_transaction_id_get
#
# Get specific Transaction
# 
# @param string $transaction_id ID of transaction to retrieve (required)
{
    my $params = {
    'transaction_id' => {
        data_type => 'string',
        description => 'ID of transaction to retrieve',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'recharge_transactions_by_transaction_id_get' } = { 
    	summary => 'Get specific Transaction',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_transactions_by_transaction_id_get {
    my ($self, %args) = @_;

    # verify the required parameter 'transaction_id' is set
    unless (exists $args{'transaction_id'}) {
      croak("Missing the required parameter 'transaction_id' when calling recharge_transactions_by_transaction_id_get");
    }

    # parse inputs
    my $_resource_path = '/recharge/transactions/{transaction_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'transaction_id'}) {
        my $_base_variable = "{" . "transaction_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'transaction_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# recharge_transactions_get
#
# Purchase a package
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'recharge_transactions_get' } = { 
    	summary => 'Purchase a package',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub recharge_transactions_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/recharge/transactions';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
