=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::PostReturnAddressApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::SwaggerClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::SwaggerClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# post_return_addresses_by_return_address_id_delete
#
# Delete specific post return address
# 
# @param int $return_address_id Return address ID (required)
{
    my $params = {
    'return_address_id' => {
        data_type => 'int',
        description => 'Return address ID',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_return_addresses_by_return_address_id_delete' } = { 
    	summary => 'Delete specific post return address',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_return_addresses_by_return_address_id_delete {
    my ($self, %args) = @_;

    # verify the required parameter 'return_address_id' is set
    unless (exists $args{'return_address_id'}) {
      croak("Missing the required parameter 'return_address_id' when calling post_return_addresses_by_return_address_id_delete");
    }

    # parse inputs
    my $_resource_path = '/post/return-addresses/{return_address_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'return_address_id'}) {
        my $_base_variable = "{" . "return_address_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'return_address_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_return_addresses_by_return_address_id_get
#
# Get specific post return address
# 
# @param int $return_address_id Return address ID (required)
{
    my $params = {
    'return_address_id' => {
        data_type => 'int',
        description => 'Return address ID',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_return_addresses_by_return_address_id_get' } = { 
    	summary => 'Get specific post return address',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_return_addresses_by_return_address_id_get {
    my ($self, %args) = @_;

    # verify the required parameter 'return_address_id' is set
    unless (exists $args{'return_address_id'}) {
      croak("Missing the required parameter 'return_address_id' when calling post_return_addresses_by_return_address_id_get");
    }

    # parse inputs
    my $_resource_path = '/post/return-addresses/{return_address_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'return_address_id'}) {
        my $_base_variable = "{" . "return_address_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'return_address_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_return_addresses_by_return_address_id_put
#
# Update post return address
# 
# @param int $return_address_id Return address ID (required)
# @param Address $return_address Address model (required)
{
    my $params = {
    'return_address_id' => {
        data_type => 'int',
        description => 'Return address ID',
        required => '1',
    },
    'return_address' => {
        data_type => 'Address',
        description => 'Address model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_return_addresses_by_return_address_id_put' } = { 
    	summary => 'Update post return address',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_return_addresses_by_return_address_id_put {
    my ($self, %args) = @_;

    # verify the required parameter 'return_address_id' is set
    unless (exists $args{'return_address_id'}) {
      croak("Missing the required parameter 'return_address_id' when calling post_return_addresses_by_return_address_id_put");
    }

    # verify the required parameter 'return_address' is set
    unless (exists $args{'return_address'}) {
      croak("Missing the required parameter 'return_address' when calling post_return_addresses_by_return_address_id_put");
    }

    # parse inputs
    my $_resource_path = '/post/return-addresses/{return_address_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'return_address_id'}) {
        my $_base_variable = "{" . "return_address_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'return_address_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'return_address'}) {
        $_body_data = $args{'return_address'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_return_addresses_get
#
# Get list of post return addresses
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_return_addresses_get' } = { 
    	summary => 'Get list of post return addresses',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_return_addresses_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/post/return-addresses';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_return_addresses_post
#
# Create post return address
# 
# @param Address $return_address Address model (required)
{
    my $params = {
    'return_address' => {
        data_type => 'Address',
        description => 'Address model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_return_addresses_post' } = { 
    	summary => 'Create post return address',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_return_addresses_post {
    my ($self, %args) = @_;

    # verify the required parameter 'return_address' is set
    unless (exists $args{'return_address'}) {
      croak("Missing the required parameter 'return_address' when calling post_return_addresses_post");
    }

    # parse inputs
    my $_resource_path = '/post/return-addresses';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'return_address'}) {
        $_body_data = $args{'return_address'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
