=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::GlobalSendingApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# list_countries_get
#
# List of countries
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'list_countries_get' } = { 
    	summary => 'List of countries',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub list_countries_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/country-list';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# user_countries_agree_post
#
# Agree to rules and regulation
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'user_countries_agree_post' } = { 
    	summary => 'Agree to rules and regulation',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub user_countries_agree_post {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/user-countries/agree';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# user_countries_get
#
# Get Countries for Global Sending
# 
{
    my $params = {
    };
    __PACKAGE__->method_documentation->{ 'user_countries_get' } = { 
    	summary => 'Get Countries for Global Sending',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub user_countries_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/user-countries';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# user_countries_post
#
# Select Countries for Global Sending
# 
# @param CountryListIds $country_list_ids Id of countr(ies) you want to select, you can get them from GET /country-list response (required)
{
    my $params = {
    'country_list_ids' => {
        data_type => 'CountryListIds',
        description => 'Id of countr(ies) you want to select, you can get them from GET /country-list response',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'user_countries_post' } = { 
    	summary => 'Select Countries for Global Sending',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub user_countries_post {
    my ($self, %args) = @_;

    # verify the required parameter 'country_list_ids' is set
    unless (exists $args{'country_list_ids'}) {
      croak("Missing the required parameter 'country_list_ids' when calling user_countries_post");
    }

    # parse inputs
    my $_resource_path = '/user-countries';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'country_list_ids'}) {
        $_body_data = $args{'country_list_ids'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
