=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::InboundSMSRulesApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# sms_inbound_automation_delete
#
# Delete inbound sms automation
# 
# @param int $inbound_rule_id Inbound rule id (required)
{
    my $params = {
    'inbound_rule_id' => {
        data_type => 'int',
        description => 'Inbound rule id',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'sms_inbound_automation_delete' } = { 
    	summary => 'Delete inbound sms automation',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub sms_inbound_automation_delete {
    my ($self, %args) = @_;

    # verify the required parameter 'inbound_rule_id' is set
    unless (exists $args{'inbound_rule_id'}) {
      croak("Missing the required parameter 'inbound_rule_id' when calling sms_inbound_automation_delete");
    }

    # parse inputs
    my $_resource_path = '/automations/sms/inbound/{inbound_rule_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'inbound_rule_id'}) {
        my $_base_variable = "{" . "inbound_rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inbound_rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# sms_inbound_automation_get
#
# Get specific inbound sms automation
# 
# @param int $inbound_rule_id Inbound rule id (required)
{
    my $params = {
    'inbound_rule_id' => {
        data_type => 'int',
        description => 'Inbound rule id',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'sms_inbound_automation_get' } = { 
    	summary => 'Get specific inbound sms automation',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub sms_inbound_automation_get {
    my ($self, %args) = @_;

    # verify the required parameter 'inbound_rule_id' is set
    unless (exists $args{'inbound_rule_id'}) {
      croak("Missing the required parameter 'inbound_rule_id' when calling sms_inbound_automation_get");
    }

    # parse inputs
    my $_resource_path = '/automations/sms/inbound/{inbound_rule_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'inbound_rule_id'}) {
        my $_base_variable = "{" . "inbound_rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inbound_rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# sms_inbound_automation_post
#
# Create new inbound sms automation
# 
# @param InboundSMSRule $inbound_sms_rule Inbound sms rule model (required)
{
    my $params = {
    'inbound_sms_rule' => {
        data_type => 'InboundSMSRule',
        description => 'Inbound sms rule model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'sms_inbound_automation_post' } = { 
    	summary => 'Create new inbound sms automation',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub sms_inbound_automation_post {
    my ($self, %args) = @_;

    # verify the required parameter 'inbound_sms_rule' is set
    unless (exists $args{'inbound_sms_rule'}) {
      croak("Missing the required parameter 'inbound_sms_rule' when calling sms_inbound_automation_post");
    }

    # parse inputs
    my $_resource_path = '/automations/sms/inbound';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'inbound_sms_rule'}) {
        $_body_data = $args{'inbound_sms_rule'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# sms_inbound_automation_put
#
# Update inbound sms automation
# 
# @param int $inbound_rule_id Inbound rule id (required)
# @param InboundSMSRule $inbound_sms_rule Inbound sms rule model (required)
{
    my $params = {
    'inbound_rule_id' => {
        data_type => 'int',
        description => 'Inbound rule id',
        required => '1',
    },
    'inbound_sms_rule' => {
        data_type => 'InboundSMSRule',
        description => 'Inbound sms rule model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'sms_inbound_automation_put' } = { 
    	summary => 'Update inbound sms automation',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub sms_inbound_automation_put {
    my ($self, %args) = @_;

    # verify the required parameter 'inbound_rule_id' is set
    unless (exists $args{'inbound_rule_id'}) {
      croak("Missing the required parameter 'inbound_rule_id' when calling sms_inbound_automation_put");
    }

    # verify the required parameter 'inbound_sms_rule' is set
    unless (exists $args{'inbound_sms_rule'}) {
      croak("Missing the required parameter 'inbound_sms_rule' when calling sms_inbound_automation_put");
    }

    # parse inputs
    my $_resource_path = '/automations/sms/inbound/{inbound_rule_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'inbound_rule_id'}) {
        my $_base_variable = "{" . "inbound_rule_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'inbound_rule_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'inbound_sms_rule'}) {
        $_body_data = $args{'inbound_sms_rule'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# sms_inbound_automations_get
#
# Get all inbound sms automations
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'sms_inbound_automations_get' } = { 
    	summary => 'Get all inbound sms automations',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub sms_inbound_automations_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/automations/sms/inbound';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
