=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::MMSApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# mms_history_export_get
#
# Export all mms history
# 
# @param string $filename Filename to download history as (required)
{
    my $params = {
    'filename' => {
        data_type => 'string',
        description => 'Filename to download history as',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_history_export_get' } = { 
    	summary => 'Export all mms history',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_history_export_get {
    my ($self, %args) = @_;

    # verify the required parameter 'filename' is set
    unless (exists $args{'filename'}) {
      croak("Missing the required parameter 'filename' when calling mms_history_export_get");
    }

    # parse inputs
    my $_resource_path = '/mms/history/export';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'filename'}) {
        $query_params->{'filename'} = $self->{api_client}->to_query_value($args{'filename'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# mms_history_get
#
# Get all mms history
# 
# @param string $q Custom query Example: from:{number},status_code:201. (optional)
# @param int $date_from Start date (optional)
# @param int $date_to End date (optional)
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'q' => {
        data_type => 'string',
        description => 'Custom query Example: from:{number},status_code:201.',
        required => '0',
    },
    'date_from' => {
        data_type => 'int',
        description => 'Start date',
        required => '0',
    },
    'date_to' => {
        data_type => 'int',
        description => 'End date',
        required => '0',
    },
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_history_get' } = { 
    	summary => 'Get all mms history',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_history_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/mms/history';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'q'}) {
        $query_params->{'q'} = $self->{api_client}->to_query_value($args{'q'});
    }

    # query params
    if ( exists $args{'date_from'}) {
        $query_params->{'date_from'} = $self->{api_client}->to_query_value($args{'date_from'});
    }

    # query params
    if ( exists $args{'date_to'}) {
        $query_params->{'date_to'} = $self->{api_client}->to_query_value($args{'date_to'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# mms_price_post
#
# Get Price for MMS sent
# 
# @param MmsMessageCollection $mms_messages MmsMessageCollection model (required)
{
    my $params = {
    'mms_messages' => {
        data_type => 'MmsMessageCollection',
        description => 'MmsMessageCollection model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_price_post' } = { 
    	summary => 'Get Price for MMS sent',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_price_post {
    my ($self, %args) = @_;

    # verify the required parameter 'mms_messages' is set
    unless (exists $args{'mms_messages'}) {
      croak("Missing the required parameter 'mms_messages' when calling mms_price_post");
    }

    # parse inputs
    my $_resource_path = '/mms/price';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'mms_messages'}) {
        $_body_data = $args{'mms_messages'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# mms_receipts_get
#
# Get all delivery receipts
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_receipts_get' } = { 
    	summary => 'Get all delivery receipts',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_receipts_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/mms/receipts';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# mms_receipts_read_put
#
# Mark delivery receipts as read
# 
# @param DateBefore $date_before DateBefore model (optional)
{
    my $params = {
    'date_before' => {
        data_type => 'DateBefore',
        description => 'DateBefore model',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_receipts_read_put' } = { 
    	summary => 'Mark delivery receipts as read',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_receipts_read_put {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/mms/receipts-read';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'date_before'}) {
        $_body_data = $args{'date_before'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# mms_send_post
#
# Send MMS
# 
# @param MmsMessageCollection $mms_messages MmsMessageCollection model (required)
{
    my $params = {
    'mms_messages' => {
        data_type => 'MmsMessageCollection',
        description => 'MmsMessageCollection model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'mms_send_post' } = { 
    	summary => 'Send MMS',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub mms_send_post {
    my ($self, %args) = @_;

    # verify the required parameter 'mms_messages' is set
    unless (exists $args{'mms_messages'}) {
      croak("Missing the required parameter 'mms_messages' when calling mms_send_post");
    }

    # parse inputs
    my $_resource_path = '/mms/send';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'mms_messages'}) {
        $_body_data = $args{'mms_messages'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
