=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::ResellerAccountApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# reseller_accounts_by_client_user_id_get
#
# Get Reseller clients Account
# 
# @param int $client_user_id User ID of client (required)
{
    my $params = {
    'client_user_id' => {
        data_type => 'int',
        description => 'User ID of client',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'reseller_accounts_by_client_user_id_get' } = { 
    	summary => 'Get Reseller clients Account',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub reseller_accounts_by_client_user_id_get {
    my ($self, %args) = @_;

    # verify the required parameter 'client_user_id' is set
    unless (exists $args{'client_user_id'}) {
      croak("Missing the required parameter 'client_user_id' when calling reseller_accounts_by_client_user_id_get");
    }

    # parse inputs
    my $_resource_path = '/reseller/accounts/{client_user_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'client_user_id'}) {
        my $_base_variable = "{" . "client_user_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'client_user_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# reseller_accounts_by_client_user_id_put
#
# Update Reseller clients Account
# 
# @param int $client_user_id User ID of client (required)
# @param ResellerAccount $reseller_account ResellerAccount model (required)
{
    my $params = {
    'client_user_id' => {
        data_type => 'int',
        description => 'User ID of client',
        required => '1',
    },
    'reseller_account' => {
        data_type => 'ResellerAccount',
        description => 'ResellerAccount model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'reseller_accounts_by_client_user_id_put' } = { 
    	summary => 'Update Reseller clients Account',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub reseller_accounts_by_client_user_id_put {
    my ($self, %args) = @_;

    # verify the required parameter 'client_user_id' is set
    unless (exists $args{'client_user_id'}) {
      croak("Missing the required parameter 'client_user_id' when calling reseller_accounts_by_client_user_id_put");
    }

    # verify the required parameter 'reseller_account' is set
    unless (exists $args{'reseller_account'}) {
      croak("Missing the required parameter 'reseller_account' when calling reseller_accounts_by_client_user_id_put");
    }

    # parse inputs
    my $_resource_path = '/reseller/accounts/{client_user_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'client_user_id'}) {
        my $_base_variable = "{" . "client_user_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'client_user_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'reseller_account'}) {
        $_body_data = $args{'reseller_account'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# reseller_accounts_get
#
# Get list of reseller accounts
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'reseller_accounts_get' } = { 
    	summary => 'Get list of reseller accounts',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub reseller_accounts_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/reseller/accounts';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# reseller_accounts_post
#
# Create reseller account
# 
# @param ResellerAccount $reseller_account ResellerAccount model (required)
{
    my $params = {
    'reseller_account' => {
        data_type => 'ResellerAccount',
        description => 'ResellerAccount model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'reseller_accounts_post' } = { 
    	summary => 'Create reseller account',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub reseller_accounts_post {
    my ($self, %args) = @_;

    # verify the required parameter 'reseller_account' is set
    unless (exists $args{'reseller_account'}) {
      croak("Missing the required parameter 'reseller_account' when calling reseller_accounts_post");
    }

    # parse inputs
    my $_resource_path = '/reseller/accounts';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'reseller_account'}) {
        $_body_data = $args{'reseller_account'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
