=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::Object::Contact;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#Contains all details for the main contact.
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::ClickSendClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'Contains all details for the main contact.',
                                  class => 'Contact',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'phone_number' => {
    	datatype => 'string',
    	base_name => 'phone_number',
    	description => 'Your phone number in E.164 format. Must be provided if no fax number or email.',
    	format => '',
    	read_only => '',
    		},
    'custom_1' => {
    	datatype => 'string',
    	base_name => 'custom_1',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'email' => {
    	datatype => 'string',
    	base_name => 'email',
    	description => 'Your email. Must be provided if no phone number or fax number.',
    	format => '',
    	read_only => '',
    		},
    'fax_number' => {
    	datatype => 'string',
    	base_name => 'fax_number',
    	description => 'Your fax number. Must be provided if no phone number or email.',
    	format => '',
    	read_only => '',
    		},
    'first_name' => {
    	datatype => 'string',
    	base_name => 'first_name',
    	description => 'Your first name.',
    	format => '',
    	read_only => '',
    		},
    'address_line_1' => {
    	datatype => 'string',
    	base_name => 'address_line_1',
    	description => 'Your street address',
    	format => '',
    	read_only => '',
    		},
    'address_line_2' => {
    	datatype => 'string',
    	base_name => 'address_line_2',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'address_city' => {
    	datatype => 'string',
    	base_name => 'address_city',
    	description => 'Your nearest city',
    	format => '',
    	read_only => '',
    		},
    'address_state' => {
    	datatype => 'string',
    	base_name => 'address_state',
    	description => 'Your current state',
    	format => '',
    	read_only => '',
    		},
    'address_postal_code' => {
    	datatype => 'string',
    	base_name => 'address_postal_code',
    	description => 'Your current postcode',
    	format => '',
    	read_only => '',
    		},
    'address_country' => {
    	datatype => 'string',
    	base_name => 'address_country',
    	description => 'Your current country',
    	format => '',
    	read_only => '',
    		},
    'organization_name' => {
    	datatype => 'string',
    	base_name => 'organization_name',
    	description => 'Your organisation name',
    	format => '',
    	read_only => '',
    		},
    'custom_2' => {
    	datatype => 'string',
    	base_name => 'custom_2',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'custom_3' => {
    	datatype => 'string',
    	base_name => 'custom_3',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'custom_4' => {
    	datatype => 'string',
    	base_name => 'custom_4',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'last_name' => {
    	datatype => 'string',
    	base_name => 'last_name',
    	description => 'Your last name',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'phone_number' => 'string',
    'custom_1' => 'string',
    'email' => 'string',
    'fax_number' => 'string',
    'first_name' => 'string',
    'address_line_1' => 'string',
    'address_line_2' => 'string',
    'address_city' => 'string',
    'address_state' => 'string',
    'address_postal_code' => 'string',
    'address_country' => 'string',
    'organization_name' => 'string',
    'custom_2' => 'string',
    'custom_3' => 'string',
    'custom_4' => 'string',
    'last_name' => 'string'
} );

__PACKAGE__->attribute_map( {
    'phone_number' => 'phone_number',
    'custom_1' => 'custom_1',
    'email' => 'email',
    'fax_number' => 'fax_number',
    'first_name' => 'first_name',
    'address_line_1' => 'address_line_1',
    'address_line_2' => 'address_line_2',
    'address_city' => 'address_city',
    'address_state' => 'address_state',
    'address_postal_code' => 'address_postal_code',
    'address_country' => 'address_country',
    'organization_name' => 'organization_name',
    'custom_2' => 'custom_2',
    'custom_3' => 'custom_3',
    'custom_4' => 'custom_4',
    'last_name' => 'last_name'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
