=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::AccountRechargeApi');

my $api = WWW::ClickSendClient::AccountRechargeApi->new();
isa_ok($api, 'WWW::ClickSendClient::AccountRechargeApi');

#
# recharge_credit_card_get test
#
{
    my $result = $api->recharge_credit_card_get();
}

#
# recharge_credit_card_put test
#
{
    my $credit_card = undef; # replace NULL with a proper value
    my $result = $api->recharge_credit_card_put(credit_card => $credit_card);
}

#
# recharge_packages_get test
#
{
    my $country = undef; # replace NULL with a proper value
    my $result = $api->recharge_packages_get(country => $country);
}

#
# recharge_purchase_by_package_id_put test
#
{
    my $package_id = undef; # replace NULL with a proper value
    my $result = $api->recharge_purchase_by_package_id_put(package_id => $package_id);
}

#
# recharge_transactions_by_transaction_id_get test
#
{
    my $transaction_id = undef; # replace NULL with a proper value
    my $result = $api->recharge_transactions_by_transaction_id_get(transaction_id => $transaction_id);
}

#
# recharge_transactions_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->recharge_transactions_get(page => $page, limit => $limit);
}


1;
