=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::ContactListApi');

my $api = WWW::ClickSendClient::ContactListApi->new();
isa_ok($api, 'WWW::ClickSendClient::ContactListApi');

#
# lists_by_list_id_delete test
#
{
    my $list_id = undef; # replace NULL with a proper value
    my $result = $api->lists_by_list_id_delete(list_id => $list_id);
}

#
# lists_by_list_id_get test
#
{
    my $list_id = undef; # replace NULL with a proper value
    my $result = $api->lists_by_list_id_get(list_id => $list_id);
}

#
# lists_by_list_id_put test
#
{
    my $list_id = undef; # replace NULL with a proper value
    my $contact_list = undef; # replace NULL with a proper value
    my $result = $api->lists_by_list_id_put(list_id => $list_id, contact_list => $contact_list);
}

#
# lists_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->lists_get(page => $page, limit => $limit);
}

#
# lists_import_by_list_id_post test
#
{
    my $list_id = undef; # replace NULL with a proper value
    my $file = undef; # replace NULL with a proper value
    my $result = $api->lists_import_by_list_id_post(list_id => $list_id, file => $file);
}

#
# lists_post test
#
{
    my $contact_list = undef; # replace NULL with a proper value
    my $result = $api->lists_post(contact_list => $contact_list);
}

#
# lists_remove_duplicates_by_list_id_put test
#
{
    my $list_id = undef; # replace NULL with a proper value
    my $fields = undef; # replace NULL with a proper value
    my $result = $api->lists_remove_duplicates_by_list_id_put(list_id => $list_id, fields => $fields);
}


1;
