=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::InboundFAXRulesApi');

my $api = WWW::ClickSendClient::InboundFAXRulesApi->new();
isa_ok($api, 'WWW::ClickSendClient::InboundFAXRulesApi');

#
# fax_inbound_automation_delete test
#
{
    my $inbound_rule_id = undef; # replace NULL with a proper value
    my $result = $api->fax_inbound_automation_delete(inbound_rule_id => $inbound_rule_id);
}

#
# fax_inbound_automation_get test
#
{
    my $inbound_rule_id = undef; # replace NULL with a proper value
    my $result = $api->fax_inbound_automation_get(inbound_rule_id => $inbound_rule_id);
}

#
# fax_inbound_automation_post test
#
{
    my $inbound_fax_rule = undef; # replace NULL with a proper value
    my $result = $api->fax_inbound_automation_post(inbound_fax_rule => $inbound_fax_rule);
}

#
# fax_inbound_automation_put test
#
{
    my $inbound_rule_id = undef; # replace NULL with a proper value
    my $inbound_fax_rule = undef; # replace NULL with a proper value
    my $result = $api->fax_inbound_automation_put(inbound_rule_id => $inbound_rule_id, inbound_fax_rule => $inbound_fax_rule);
}

#
# fax_inbound_automations_get test
#
{
    my $q = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->fax_inbound_automations_get(q => $q, page => $page, limit => $limit);
}


1;
