=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::MMSApi');

my $api = WWW::ClickSendClient::MMSApi->new();
isa_ok($api, 'WWW::ClickSendClient::MMSApi');

#
# mms_history_export_get test
#
{
    my $filename = undef; # replace NULL with a proper value
    my $result = $api->mms_history_export_get(filename => $filename);
}

#
# mms_history_get test
#
{
    my $q = undef; # replace NULL with a proper value
    my $date_from = undef; # replace NULL with a proper value
    my $date_to = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->mms_history_get(q => $q, date_from => $date_from, date_to => $date_to, page => $page, limit => $limit);
}

#
# mms_price_post test
#
{
    my $mms_messages = undef; # replace NULL with a proper value
    my $result = $api->mms_price_post(mms_messages => $mms_messages);
}

#
# mms_receipts_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->mms_receipts_get(page => $page, limit => $limit);
}

#
# mms_receipts_read_put test
#
{
    my $date_before = undef; # replace NULL with a proper value
    my $result = $api->mms_receipts_read_put(date_before => $date_before);
}

#
# mms_send_post test
#
{
    my $mms_messages = undef; # replace NULL with a proper value
    my $result = $api->mms_send_post(mms_messages => $mms_messages);
}


1;
