=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::NumberApi');

my $api = WWW::SwaggerClient::NumberApi->new();
isa_ok($api, 'WWW::SwaggerClient::NumberApi');

#
# numbers_buy_by_dedicated_number_post test
#
{
    my $dedicated_number = undef; # replace NULL with a proper value
    my $result = $api->numbers_buy_by_dedicated_number_post(dedicated_number => $dedicated_number);
}

#
# numbers_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->numbers_get(page => $page, limit => $limit);
}

#
# numbers_search_by_country_get test
#
{
    my $country = undef; # replace NULL with a proper value
    my $search = undef; # replace NULL with a proper value
    my $search_type = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->numbers_search_by_country_get(country => $country, search => $search, search_type => $search_type, page => $page, limit => $limit);
}


1;
