=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::SMSDeliveryReceiptRulesApi');

my $api = WWW::ClickSendClient::SMSDeliveryReceiptRulesApi->new();
isa_ok($api, 'WWW::ClickSendClient::SMSDeliveryReceiptRulesApi');

#
# sms_delivery_receipt_automation_delete test
#
{
    my $receipt_rule_id = undef; # replace NULL with a proper value
    my $result = $api->sms_delivery_receipt_automation_delete(receipt_rule_id => $receipt_rule_id);
}

#
# sms_delivery_receipt_automation_get test
#
{
    my $receipt_rule_id = undef; # replace NULL with a proper value
    my $result = $api->sms_delivery_receipt_automation_get(receipt_rule_id => $receipt_rule_id);
}

#
# sms_delivery_receipt_automation_post test
#
{
    my $delivery_receipt_rule = undef; # replace NULL with a proper value
    my $result = $api->sms_delivery_receipt_automation_post(delivery_receipt_rule => $delivery_receipt_rule);
}

#
# sms_delivery_receipt_automation_put test
#
{
    my $receipt_rule_id = undef; # replace NULL with a proper value
    my $delivery_receipt_rule = undef; # replace NULL with a proper value
    my $result = $api->sms_delivery_receipt_automation_put(receipt_rule_id => $receipt_rule_id, delivery_receipt_rule => $delivery_receipt_rule);
}

#
# sms_delivery_receipt_automations_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->sms_delivery_receipt_automations_get(page => $page, limit => $limit);
}


1;
