=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::SubaccountApi');

my $api = WWW::ClickSendClient::SubaccountApi->new();
isa_ok($api, 'WWW::ClickSendClient::SubaccountApi');

#
# subaccounts_by_subaccount_id_delete test
#
{
    my $subaccount_id = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_by_subaccount_id_delete(subaccount_id => $subaccount_id);
}

#
# subaccounts_by_subaccount_id_get test
#
{
    my $subaccount_id = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_by_subaccount_id_get(subaccount_id => $subaccount_id);
}

#
# subaccounts_by_subaccount_id_put test
#
{
    my $subaccount_id = undef; # replace NULL with a proper value
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_by_subaccount_id_put(subaccount_id => $subaccount_id, subaccount => $subaccount);
}

#
# subaccounts_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_get(page => $page, limit => $limit);
}

#
# subaccounts_post test
#
{
    my $subaccount = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_post(subaccount => $subaccount);
}

#
# subaccounts_regen_api_key_by_subaccount_id_put test
#
{
    my $subaccount_id = undef; # replace NULL with a proper value
    my $result = $api->subaccounts_regen_api_key_by_subaccount_id_put(subaccount_id => $subaccount_id);
}


1;
