=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::UserEmailTemplatesApi');

my $api = WWW::ClickSendClient::UserEmailTemplatesApi->new();
isa_ok($api, 'WWW::ClickSendClient::UserEmailTemplatesApi');

#
# email_template_delete test
#
{
    my $template_id = undef; # replace NULL with a proper value
    my $result = $api->email_template_delete(template_id => $template_id);
}

#
# email_template_get test
#
{
    my $template_id = undef; # replace NULL with a proper value
    my $result = $api->email_template_get(template_id => $template_id);
}

#
# email_template_post test
#
{
    my $email_template = undef; # replace NULL with a proper value
    my $result = $api->email_template_post(email_template => $email_template);
}

#
# email_template_put test
#
{
    my $template_id = undef; # replace NULL with a proper value
    my $email_template = undef; # replace NULL with a proper value
    my $result = $api->email_template_put(template_id => $template_id, email_template => $email_template);
}

#
# email_templates_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->email_templates_get(page => $page, limit => $limit);
}


1;
