=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by ClickSend Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::ClickSendClient::VoiceApi');

my $api = WWW::ClickSendClient::VoiceApi->new();
isa_ok($api, 'WWW::ClickSendClient::VoiceApi');

#
# voice_cancel_all_put test
#
{
    my $result = $api->voice_cancel_all_put();
}

#
# voice_cancel_by_message_id_put test
#
{
    my $message_id = undef; # replace NULL with a proper value
    my $result = $api->voice_cancel_by_message_id_put(message_id => $message_id);
}

#
# voice_history_export_get test
#
{
    my $filename = undef; # replace NULL with a proper value
    my $result = $api->voice_history_export_get(filename => $filename);
}

#
# voice_history_get test
#
{
    my $date_from = undef; # replace NULL with a proper value
    my $date_to = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->voice_history_get(date_from => $date_from, date_to => $date_to, page => $page, limit => $limit);
}

#
# voice_lang_get test
#
{
    my $result = $api->voice_lang_get();
}

#
# voice_price_post test
#
{
    my $voice_messages = undef; # replace NULL with a proper value
    my $result = $api->voice_price_post(voice_messages => $voice_messages);
}

#
# voice_receipts_get test
#
{
    my $page = undef; # replace NULL with a proper value
    my $limit = undef; # replace NULL with a proper value
    my $result = $api->voice_receipts_get(page => $page, limit => $limit);
}

#
# voice_send_post test
#
{
    my $voice_messages = undef; # replace NULL with a proper value
    my $result = $api->voice_send_post(voice_messages => $voice_messages);
}


1;
