=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::Object::VoiceMessage;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;


use base ("Class::Accessor", "Class::Data::Inheritable");


#
#VoiceMessage fields: source, to, list_id, body, lang, voice, schedule, custom_string, country
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

ClickSend v3 API

 This is an official SDK for [ClickSend](https://clicksend.com)  Below you will find a current list of the available methods for clicksend.  *NOTE: You will need to create a free account to use the API. You can register [here](https://dashboard.clicksend.com/#/signup/step1/)..* 

OpenAPI spec version: 3.1
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::ClickSendClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'VoiceMessage fields: source, to, list_id, body, lang, voice, schedule, custom_string, country',
                                  class => 'VoiceMessage',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'to' => {
    	datatype => 'string',
    	base_name => 'to',
    	description => 'Your phone number in E.164 format.',
    	format => '',
    	read_only => '',
    		},
    'body' => {
    	datatype => 'string',
    	base_name => 'body',
    	description => 'Biscuit uv3nlCOjRk croissant chocolate lollipop chocolate muffin.',
    	format => '',
    	read_only => '',
    		},
    'voice' => {
    	datatype => 'string',
    	base_name => 'voice',
    	description => 'Either &#39;female&#39; or &#39;male&#39;.',
    	format => '',
    	read_only => '',
    		},
    'custom_string' => {
    	datatype => 'string',
    	base_name => 'custom_string',
    	description => 'Your reference. Will be passed back with all replies and delivery reports.',
    	format => '',
    	read_only => '',
    		},
    'country' => {
    	datatype => 'string',
    	base_name => 'country',
    	description => 'The country of the recipient.',
    	format => '',
    	read_only => '',
    		},
    'source' => {
    	datatype => 'string',
    	base_name => 'source',
    	description => 'Your method of sending e.g. &#39;wordpress&#39;, &#39;php&#39;, &#39;c#&#39;.',
    	format => '',
    	read_only => '',
    		},
    'list_id' => {
    	datatype => 'int',
    	base_name => 'list_id',
    	description => 'Your list ID if sending to a whole list. Can be used instead of &#39;to&#39;.',
    	format => '',
    	read_only => '',
    		},
    'lang' => {
    	datatype => 'string',
    	base_name => 'lang',
    	description => 'au (string, required) - See section on available languages.',
    	format => '',
    	read_only => '',
    		},
    'schedule' => {
    	datatype => 'int',
    	base_name => 'schedule',
    	description => 'Leave blank for immediate delivery. Your schedule time in unix format http://help.clicksend.com/what-is-a-unix-timestamp',
    	format => '',
    	read_only => '',
    		},
    'require_input' => {
    	datatype => 'int',
    	base_name => 'require_input',
    	description => 'Whether you want to receive a keypress from the call recipient',
    	format => '',
    	read_only => '',
    		},
    'machine_detection' => {
    	datatype => 'int',
    	base_name => 'machine_detection',
    	description => 'Whether to attempt to detect an answering machine or voicemail service and leave a message',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'to' => 'string',
    'body' => 'string',
    'voice' => 'string',
    'custom_string' => 'string',
    'country' => 'string',
    'source' => 'string',
    'list_id' => 'int',
    'lang' => 'string',
    'schedule' => 'int',
    'require_input' => 'int',
    'machine_detection' => 'int'
} );

__PACKAGE__->attribute_map( {
    'to' => 'to',
    'body' => 'body',
    'voice' => 'voice',
    'custom_string' => 'custom_string',
    'country' => 'country',
    'source' => 'source',
    'list_id' => 'list_id',
    'lang' => 'lang',
    'schedule' => 'schedule',
    'require_input' => 'require_input',
    'machine_detection' => 'machine_detection'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
