=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::SwaggerClient::PostDirectMailApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::SwaggerClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::SwaggerClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::SwaggerClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# post_direct_mail_campaigns_get
#
# Get direct mail campaigns
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_direct_mail_campaigns_get' } = { 
    	summary => 'Get direct mail campaigns',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_direct_mail_campaigns_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/post/direct-mail/campaigns';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_direct_mail_campaigns_price_post
#
# Calculate direct mail campaign price
# 
# @param PostDirectMail $post_direct_mail PostDirectMail model (required)
{
    my $params = {
    'post_direct_mail' => {
        data_type => 'PostDirectMail',
        description => 'PostDirectMail model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_direct_mail_campaigns_price_post' } = { 
    	summary => 'Calculate direct mail campaign price',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_direct_mail_campaigns_price_post {
    my ($self, %args) = @_;

    # verify the required parameter 'post_direct_mail' is set
    unless (exists $args{'post_direct_mail'}) {
      croak("Missing the required parameter 'post_direct_mail' when calling post_direct_mail_campaigns_price_post");
    }

    # parse inputs
    my $_resource_path = '/post/direct-mail/campaigns/price';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'post_direct_mail'}) {
        $_body_data = $args{'post_direct_mail'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_direct_mail_campaigns_send_post
#
# Send direct mail campaign
# 
# @param PostDirectMail $post_direct_mail PostDirectMail model (required)
{
    my $params = {
    'post_direct_mail' => {
        data_type => 'PostDirectMail',
        description => 'PostDirectMail model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_direct_mail_campaigns_send_post' } = { 
    	summary => 'Send direct mail campaign',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_direct_mail_campaigns_send_post {
    my ($self, %args) = @_;

    # verify the required parameter 'post_direct_mail' is set
    unless (exists $args{'post_direct_mail'}) {
      croak("Missing the required parameter 'post_direct_mail' when calling post_direct_mail_campaigns_send_post");
    }

    # parse inputs
    my $_resource_path = '/post/direct-mail/campaigns/send';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'post_direct_mail'}) {
        $_body_data = $args{'post_direct_mail'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_direct_mail_locations_search_by_country_get
#
# Search for a location
# 
# @param string $country Country Code to search (required)
# @param string $q Search term (e.g. post code, city name) (required)
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'country' => {
        data_type => 'string',
        description => 'Country Code to search',
        required => '1',
    },
    'q' => {
        data_type => 'string',
        description => 'Search term (e.g. post code, city name)',
        required => '1',
    },
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_direct_mail_locations_search_by_country_get' } = { 
    	summary => 'Search for a location',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_direct_mail_locations_search_by_country_get {
    my ($self, %args) = @_;

    # verify the required parameter 'country' is set
    unless (exists $args{'country'}) {
      croak("Missing the required parameter 'country' when calling post_direct_mail_locations_search_by_country_get");
    }

    # verify the required parameter 'q' is set
    unless (exists $args{'q'}) {
      croak("Missing the required parameter 'q' when calling post_direct_mail_locations_search_by_country_get");
    }

    # parse inputs
    my $_resource_path = '/post/direct-mail/locations/search/{country}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'q'}) {
        $query_params->{'q'} = $self->{api_client}->to_query_value($args{'q'});
    }

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    # path params
    if ( exists $args{'country'}) {
        my $_base_variable = "{" . "country" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'country'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
