=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::PostPostcardApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# post_postcards_history_export_get
#
# Export postcard history to a CSV file
# 
# @param string $filename Filename to export to (required)
{
    my $params = {
    'filename' => {
        data_type => 'string',
        description => 'Filename to export to',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_postcards_history_export_get' } = { 
    	summary => 'Export postcard history to a CSV file',
        params => $params,
        returns => 'File',
        };
}
# @return File
#
sub post_postcards_history_export_get {
    my ($self, %args) = @_;

    # verify the required parameter 'filename' is set
    unless (exists $args{'filename'}) {
      croak("Missing the required parameter 'filename' when calling post_postcards_history_export_get");
    }

    # parse inputs
    my $_resource_path = '/post/postcards/history/export';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json', 'application/csv');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'filename'}) {
        $query_params->{'filename'} = $self->{api_client}->to_query_value($args{'filename'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('File', $response);
    return $_response_object;
}

#
# post_postcards_history_get
#
# Retrieve the history of postcards sent or scheduled
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_postcards_history_get' } = { 
    	summary => 'Retrieve the history of postcards sent or scheduled',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_postcards_history_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/post/postcards/history';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_postcards_price_post
#
# Calculate price for sending one or more postcards
# 
# @param PostPostcard $post_postcards PostPostcard model (required)
{
    my $params = {
    'post_postcards' => {
        data_type => 'PostPostcard',
        description => 'PostPostcard model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_postcards_price_post' } = { 
    	summary => 'Calculate price for sending one or more postcards',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_postcards_price_post {
    my ($self, %args) = @_;

    # verify the required parameter 'post_postcards' is set
    unless (exists $args{'post_postcards'}) {
      croak("Missing the required parameter 'post_postcards' when calling post_postcards_price_post");
    }

    # parse inputs
    my $_resource_path = '/post/postcards/price';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'post_postcards'}) {
        $_body_data = $args{'post_postcards'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# post_postcards_send_post
#
# Send one or more postcards
# 
# @param PostPostcard $post_postcards PostPostcard model (required)
{
    my $params = {
    'post_postcards' => {
        data_type => 'PostPostcard',
        description => 'PostPostcard model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'post_postcards_send_post' } = { 
    	summary => 'Send one or more postcards',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub post_postcards_send_post {
    my ($self, %args) = @_;

    # verify the required parameter 'post_postcards' is set
    unless (exists $args{'post_postcards'}) {
      croak("Missing the required parameter 'post_postcards' when calling post_postcards_send_post");
    }

    # parse inputs
    my $_resource_path = '/post/postcards/send';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'post_postcards'}) {
        $_body_data = $args{'post_postcards'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
