=begin comment

ClickSend v3 REST API

 This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package WWW::ClickSendClient::SubaccountApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::ClickSendClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::ClickSendClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::ClickSendClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# subaccounts_by_subaccount_id_delete
#
# Delete a subaccount
# 
# @param int $subaccount_id ID of subaccount to delete (required)
{
    my $params = {
    'subaccount_id' => {
        data_type => 'int',
        description => 'ID of subaccount to delete',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_by_subaccount_id_delete' } = { 
    	summary => 'Delete a subaccount',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_by_subaccount_id_delete {
    my ($self, %args) = @_;

    # verify the required parameter 'subaccount_id' is set
    unless (exists $args{'subaccount_id'}) {
      croak("Missing the required parameter 'subaccount_id' when calling subaccounts_by_subaccount_id_delete");
    }

    # parse inputs
    my $_resource_path = '/subaccounts/{subaccount_id}';

    my $_method = 'DELETE';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'subaccount_id'}) {
        my $_base_variable = "{" . "subaccount_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'subaccount_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# subaccounts_by_subaccount_id_get
#
# Get specific subaccount
# 
# @param int $subaccount_id ID of subaccount to get (required)
{
    my $params = {
    'subaccount_id' => {
        data_type => 'int',
        description => 'ID of subaccount to get',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_by_subaccount_id_get' } = { 
    	summary => 'Get specific subaccount',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_by_subaccount_id_get {
    my ($self, %args) = @_;

    # verify the required parameter 'subaccount_id' is set
    unless (exists $args{'subaccount_id'}) {
      croak("Missing the required parameter 'subaccount_id' when calling subaccounts_by_subaccount_id_get");
    }

    # parse inputs
    my $_resource_path = '/subaccounts/{subaccount_id}';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'subaccount_id'}) {
        my $_base_variable = "{" . "subaccount_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'subaccount_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# subaccounts_by_subaccount_id_put
#
# Update subaccount
# 
# @param int $subaccount_id ID of subaccount to update (required)
# @param Subaccount $subaccount Subaccount model (required)
{
    my $params = {
    'subaccount_id' => {
        data_type => 'int',
        description => 'ID of subaccount to update',
        required => '1',
    },
    'subaccount' => {
        data_type => 'Subaccount',
        description => 'Subaccount model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_by_subaccount_id_put' } = { 
    	summary => 'Update subaccount',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_by_subaccount_id_put {
    my ($self, %args) = @_;

    # verify the required parameter 'subaccount_id' is set
    unless (exists $args{'subaccount_id'}) {
      croak("Missing the required parameter 'subaccount_id' when calling subaccounts_by_subaccount_id_put");
    }

    # verify the required parameter 'subaccount' is set
    unless (exists $args{'subaccount'}) {
      croak("Missing the required parameter 'subaccount' when calling subaccounts_by_subaccount_id_put");
    }

    # parse inputs
    my $_resource_path = '/subaccounts/{subaccount_id}';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'subaccount_id'}) {
        my $_base_variable = "{" . "subaccount_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'subaccount_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # body params
    if ( exists $args{'subaccount'}) {
        $_body_data = $args{'subaccount'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# subaccounts_get
#
# Get all subaccounts
# 
# @param int $page Page number (optional, default to 1)
# @param int $limit Number of records per page (optional, default to 10)
{
    my $params = {
    'page' => {
        data_type => 'int',
        description => 'Page number',
        required => '0',
    },
    'limit' => {
        data_type => 'int',
        description => 'Number of records per page',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_get' } = { 
    	summary => 'Get all subaccounts',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_get {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/subaccounts';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'page'}) {
        $query_params->{'page'} = $self->{api_client}->to_query_value($args{'page'});
    }

    # query params
    if ( exists $args{'limit'}) {
        $query_params->{'limit'} = $self->{api_client}->to_query_value($args{'limit'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# subaccounts_post
#
# Create new subaccount
# 
# @param Subaccount $subaccount Subaccount model (required)
{
    my $params = {
    'subaccount' => {
        data_type => 'Subaccount',
        description => 'Subaccount model',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_post' } = { 
    	summary => 'Create new subaccount',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_post {
    my ($self, %args) = @_;

    # verify the required parameter 'subaccount' is set
    unless (exists $args{'subaccount'}) {
      croak("Missing the required parameter 'subaccount' when calling subaccounts_post");
    }

    # parse inputs
    my $_resource_path = '/subaccounts';

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    my $_body_data;
    # body params
    if ( exists $args{'subaccount'}) {
        $_body_data = $args{'subaccount'};
    }

    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# subaccounts_regen_api_key_by_subaccount_id_put
#
# Regenerate an API Key
# 
# @param int $subaccount_id ID of subaccount to regenerate API key for (required)
{
    my $params = {
    'subaccount_id' => {
        data_type => 'int',
        description => 'ID of subaccount to regenerate API key for',
        required => '1',
    },
    };
    __PACKAGE__->method_documentation->{ 'subaccounts_regen_api_key_by_subaccount_id_put' } = { 
    	summary => 'Regenerate an API Key',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub subaccounts_regen_api_key_by_subaccount_id_put {
    my ($self, %args) = @_;

    # verify the required parameter 'subaccount_id' is set
    unless (exists $args{'subaccount_id'}) {
      croak("Missing the required parameter 'subaccount_id' when calling subaccounts_regen_api_key_by_subaccount_id_put");
    }

    # parse inputs
    my $_resource_path = '/subaccounts/{subaccount_id}/regen-api-key';

    my $_method = 'PUT';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # path params
    if ( exists $args{'subaccount_id'}) {
        my $_base_variable = "{" . "subaccount_id" . "}";
        my $_base_value = $self->{api_client}->to_path_value($args{'subaccount_id'});
        $_resource_path =~ s/$_base_variable/$_base_value/g;
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(BasicAuth )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

1;
